FROM node:18-alpine

WORKDIR /app
# package Json and package-lock Json files COPY karene cmd hae dono eksaath COPY karne se npm install fast ho jata hae kyuki dono files ek sath copy ho jati hae
COPY package*.json ./
RUN npm install


COPY  . .

EXPOSE 3000

CMD [ "npm", "start" ]